"""prepaid_wallet

Revision ID: 7a171d0f4508
Revises: b2dc10d4e059
"""

from alembic import op
import sqlalchemy as sa

revision = "7a171d0f4508"
down_revision = "b2dc10d4e059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_allocations",
        sa.Column("purchase_order_id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purchase_order_id", "payment_id"),
    )
    op.create_index(
        op.f("ix_wallet_allocations_payment_id"), "wallet_allocations", ["payment_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_allocations_purchase_order_id"),
        "wallet_allocations",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "wallet_entries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount <> 0"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_wallet_entries_user_id"), "wallet_entries", ["user_id"], unique=False)
    op.add_column("grants", sa.Column("purchase_order_id", sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "grants", ["purchase_order_id"])
    op.create_foreign_key(None, "grants", "orders", ["purchase_order_id"], ["id"])
    op.add_column(
        "orders", sa.Column("funding_source", sa.String(length=16), server_default="legacy", nullable=False)
    )
    op.alter_column("orders", "product_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("orders", "plan_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("users", sa.Column("balance_stars", sa.BigInteger(), server_default="0", nullable=False))
    op.create_check_constraint("wallet_nonnegative", "users", "balance_stars >= 0")
    op.create_check_constraint(
        "order_funding_shape",
        "orders",
        "(funding_source = 'topup' AND product_id IS NULL AND plan_id IS NULL AND billing_type = 'topup') OR "
        "(funding_source IN ('legacy','wallet') AND product_id IS NOT NULL AND plan_id IS NOT NULL)",
    )
    # Preserve snapshots in old orders; only future sales switch to one-time access.
    op.execute(
        "UPDATE plans SET billing_type = 'fixed', duration_days = 30 WHERE billing_type = 'recurring_30d'"
    )
    op.execute("""DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'shop_app') THEN
        REVOKE UPDATE ON wallet_entries, wallet_allocations FROM shop_app;
      END IF;
    END $$""")


def downgrade():
    raise RuntimeError("Destructive downgrade disabled. Restore a verified backup into a separate database.")
